// <auto-generated />
using System;
using FoodOrdering.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FoodOrdering.Infrastructure.Migrations
{
    [DbContext(typeof(FoodOrderingContext))]
    [Migration("20220406135613_AddDishMenuDishEntityAndOwnedEntityNutrients")]
    partial class AddDishMenuDishEntityAndOwnedEntityNutrients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("FoodOrdering.Domain.Entities.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("FoodOrdering.Domain.Entities.DishMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("ReadyToOrder")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DishMenus");
                });

            modelBuilder.Entity("FoodOrdering.Domain.Entities.DishMenuDish", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishMenuId")
                        .HasColumnType("uuid");

                    b.HasKey("DishId", "DishMenuId");

                    b.HasIndex("DishMenuId");

                    b.ToTable("DishMenuDishes");
                });

            modelBuilder.Entity("FoodOrdering.Domain.Entities.Dish", b =>
                {
                    b.OwnsOne("FoodOrdering.Domain.Entities.Nutrients", "Nutrients", b1 =>
                        {
                            b1.Property<Guid>("DishId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Calories")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Carbohydrates")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Fats")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Proteins")
                                .HasColumnType("double precision");

                            b1.HasKey("DishId");

                            b1.ToTable("Dishes");

                            b1.WithOwner()
                                .HasForeignKey("DishId");
                        });

                    b.Navigation("Nutrients");
                });

            modelBuilder.Entity("FoodOrdering.Domain.Entities.DishMenuDish", b =>
                {
                    b.HasOne("FoodOrdering.Domain.Entities.Dish", "Dish")
                        .WithMany("DishMenuDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrdering.Domain.Entities.DishMenu", "DishMenu")
                        .WithMany("DishMenuDishes")
                        .HasForeignKey("DishMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("DishMenu");
                });

            modelBuilder.Entity("FoodOrdering.Domain.Entities.Dish", b =>
                {
                    b.Navigation("DishMenuDishes");
                });

            modelBuilder.Entity("FoodOrdering.Domain.Entities.DishMenu", b =>
                {
                    b.Navigation("DishMenuDishes");
                });
#pragma warning restore 612, 618
        }
    }
}
